#!/bin/bash

#SBATCH -J rend1
#SBATCH -o rend1.out
#SBATCH -p pbatch
#SBATCH -N 4
#SBATCH -n 128
#SBATCH --ntasks-per-node=32
#SBATCH -t 24:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=hanul@stanford.edu

WORKDIR='/p/lustre2/hwang8/helmholtz/setupcase'
export WORKDIR
### ---------------------------------------
### BEGINNING OF EXECUTION
### ---------------------------------------

echo The master node of this job is `hostname`
echo This job runs on the following nodes:
echo `scontrol show hostname $SLURM_JOB_NODELIST`
echo "Starting at `date`"
echo "Running on hosts: $SLURM_NODELIST"
echo "Running on $SLURM_NNODES nodes."
echo "Running on $SLURM_NPROCS processors."
echo "Current working directory is `echo $WORKDIR`"
echo
echo Output from code
echo ----------------

# module
#module load ensight
export PATH=$PATH:/g/g92/hwang8/blender_install/blender-2.93.4-linux-x64/

# Run your commends
blender -b -P ./script1.py
#srun -n 32 /g/g92/hwang8/cascade/helmholtz_vof/nextgen/bin/charles_vof.exe -i ./charles_vof.in
